server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/subscribly
    username: subscribly_user
    password: 1
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # Auto-create tables (for development)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  devtools:
    restart:
      enabled: false   # <<< IMPORTANT: disables old config reload

logging:
  level:
    org.hibernate.SQL: debug
